services:
  - type: web
    name: globiq-password-manager
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: singapore
    healthCheckPath: /api/health
    port: 3000
    envVars:      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://vincentnbation1:Zp8hAe473OmcwjGS@cluster0.zu5suxb.mongodb.net/passwordmanager?retryWrites=true&w=majority
      - key: ENCRYPTION_KEY
        value: Qw8rT2vB5nL6pZ1xJ7sM3eV0aH9bC4dF
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOW-FROM https://teams.microsoft.com
